// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: credentials.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCredential = `-- name: CreateCredential :exec
INSERT INTO credentials (
    id, user_id, public_key, sign_count, transports, aaguid, attestation_format
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
`

type CreateCredentialParams struct {
	ID                string
	UserID            int32
	PublicKey         []byte
	SignCount         int64
	Transports        []string
	Aaguid            pgtype.UUID
	AttestationFormat pgtype.Text
}

func (q *Queries) CreateCredential(ctx context.Context, arg CreateCredentialParams) error {
	_, err := q.db.Exec(ctx, createCredential,
		arg.ID,
		arg.UserID,
		arg.PublicKey,
		arg.SignCount,
		arg.Transports,
		arg.Aaguid,
		arg.AttestationFormat,
	)
	return err
}

const getCredentialsByUserID = `-- name: GetCredentialsByUserID :many
SELECT id, user_id, public_key, sign_count, transports, aaguid, attestation_format, created_at FROM credentials WHERE user_id = $1
`

func (q *Queries) GetCredentialsByUserID(ctx context.Context, userID int32) ([]Credential, error) {
	rows, err := q.db.Query(ctx, getCredentialsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Credential
	for rows.Next() {
		var i Credential
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PublicKey,
			&i.SignCount,
			&i.Transports,
			&i.Aaguid,
			&i.AttestationFormat,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
