// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Credential struct {
	ID                []byte
	UserID            uuid.UUID
	PublicKey         []byte
	SignCount         int64
	Transports        []string
	Aaguid            uuid.UUID
	AttestationFormat pgtype.Text
	BackupEligible    bool
	BackupState       bool
	CreatedAt         pgtype.Timestamptz
	LastUsedAt        pgtype.Timestamptz
}

type User struct {
	ID        uuid.UUID
	Username  string
	Role      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	IsActive  bool
}

type WebauthnSession struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Data      []byte
	Purpose   string
	CreatedAt pgtype.Timestamp
	ExpiresAt pgtype.Timestamp
}
